<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Furnace\Controller\Job'            => __DIR__ . '/src/Furnace/Controller/Job.php',
    'Furnace\Service\Job'               => __DIR__ . '/src/Furnace/Service/Job.php',
    'Furnace\Entity\Definition\Job'     => __DIR__ . '/src/Furnace/Entity/Definition/Job.php',
    'Furnace\Entity\Definition\History' => __DIR__ . '/src/Furnace/Entity/Definition/History.php',
    'Furnace\Entity\Job'                => __DIR__ . '/src/Furnace/Entity/Job.php',
    'Furnace\Entity\History'            => __DIR__ . '/src/Furnace/Entity/History.php',
    'Furnace\Entity\Filter\Job'         => __DIR__ . '/src/Furnace/Entity/Filter/Job.php',
    'Furnace\Entity\Filter\History'     => __DIR__ . '/src/Furnace/Entity/Filter/History.php',
    'Furnace\Entity\Form\Job'           => __DIR__ . '/src/Furnace/Entity/Form/Job.php',
    'Furnace\Factory\Controller\Job'    => __DIR__ . '/src/Furnace/Factory/Controller/Job.php',
    'Furnace\Factory\Service\Job'       => __DIR__ . '/src/Furnace/Factory/Service/Job.php',
    'Furnace\Factory\Mapper\Job'        => __DIR__ . '/src/Furnace/Factory/Mapper/Job.php',
    'Furnace\Factory\Adapter\Mongo'     => __DIR__ . '/src/Furnace/Factory/Adapter/Mongo.php',
    'Furnace\Module'                    => __DIR__ . '/Module.php',
);