<?php
namespace Furnace\Entity\Form;

/**
 * Job Form (auto-generated by the Contain module)
 *
 * This instance should not be edited directly. Edit the definition file instead
 * and recompile.
 */
class Job extends \Zend\Form\Form
{
    /**
     * Creates form fields for each of the entity properties.
     *
     * @return  $this
     */
    public function __construct()
    {
        parent::__construct('Job');
        $this->setInputFilter(new \Furnace\Entity\Filter\Job());

        $factory = new \Zend\Form\Factory();

        $this->add($factory->createElement(array(
            'name' => 'name',
            'type' => 'Zend\\Form\\Element\\Text',
            'options' => array (
  'label' => 'Name',
  'help-block' => 'Unique name used to identify the job.',
),
            'attributes' => array (
  'required' => true,
  'class' => 'input-large',
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'description',
            'type' => 'textarea',
            'options' => array (
  'label' => 'Description',
  'help-block' => 'Longer description describing what the job does.',
),
            'attributes' => array (
  'rows' => 2,
  'class' => 'input-xlarge',
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'priority',
            'type' => 'select',
            'options' => array (
  'label' => 'Priority',
  'help-block' => 'Job priority in relation to other jobs, jobs with higher priorities are started first.',
  'value_options' => 
  array (
    1 => '1',
    2 => '2',
    3 => '3',
    4 => '4',
    5 => '5',
    6 => '6',
    7 => '7',
    8 => '8',
    9 => '9',
    10 => '10',
    11 => '11',
    12 => '12',
    13 => '13',
    14 => '14',
    15 => '15',
    16 => '16',
    17 => '17',
    18 => '18',
    19 => '19',
    20 => '20',
    21 => '21',
    22 => '22',
    23 => '23',
    24 => '24',
    25 => '25',
    26 => '26',
    27 => '27',
    28 => '28',
    29 => '29',
    30 => '30',
    31 => '31',
    32 => '32',
    33 => '33',
    34 => '34',
    35 => '35',
    36 => '36',
    37 => '37',
    38 => '38',
    39 => '39',
    40 => '40',
    41 => '41',
    42 => '42',
    43 => '43',
    44 => '44',
    45 => '45',
    46 => '46',
    47 => '47',
    48 => '48',
    49 => '49',
    50 => '50',
    51 => '51',
    52 => '52',
    53 => '53',
    54 => '54',
    55 => '55',
    56 => '56',
    57 => '57',
    58 => '58',
    59 => '59',
    60 => '60',
    61 => '61',
    62 => '62',
    63 => '63',
    64 => '64',
    65 => '65',
    66 => '66',
    67 => '67',
    68 => '68',
    69 => '69',
    70 => '70',
    71 => '71',
    72 => '72',
    73 => '73',
    74 => '74',
    75 => '75',
    76 => '76',
    77 => '77',
    78 => '78',
    79 => '79',
    80 => '80',
    81 => '81',
    82 => '82',
    83 => '83',
    84 => '84',
    85 => '85',
    86 => '86',
    87 => '87',
    88 => '88',
    89 => '89',
    90 => '90',
    91 => '91',
    92 => '92',
    93 => '93',
    94 => '94',
    95 => '95',
    96 => '96',
    97 => '97',
    98 => '98',
    99 => '99',
    100 => '100',
  ),
),
            'attributes' => array (
  'class' => 'input-small',
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'schedule',
            'type' => 'select',
            'options' => array (
  'label' => 'Schedule',
  'value_options' => 
  array (
    'once' => 'Once',
    'daily' => 'Daily',
    'weekly' => 'Weekly',
    'monthly' => 'Monthly',
  ),
),
            'attributes' => array (
  'class' => 'input-medium',
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'startAt',
            'type' => 'date',
            'options' => array (
  'label' => 'Starts',
  'class' => 'input-large',
  'help-block' => 'Uses the time and/or date depending on the type of schedule.',
),
            'attributes' => array (
  'required' => true,
  'class' => 'input-medium',
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'queuedAt',
            'type' => 'Zend\\Form\\Element\\Text',
            'options' => array (
),
            'attributes' => array (
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'startedAt',
            'type' => 'Zend\\Form\\Element\\Text',
            'options' => array (
),
            'attributes' => array (
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'completedAt',
            'type' => 'Zend\\Form\\Element\\Text',
            'options' => array (
),
            'attributes' => array (
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'percentComplete',
            'type' => 'Zend\\Form\\Element\\Text',
            'options' => array (
),
            'attributes' => array (
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'error',
            'type' => 'Zend\\Form\\Element\\Text',
            'options' => array (
),
            'attributes' => array (
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'pidOf',
            'type' => 'Zend\\Form\\Element\\Text',
            'options' => array (
),
            'attributes' => array (
),
        )));

        $this->add($factory->createElement(array(
            'name' => 'pidCmd',
            'type' => 'Zend\\Form\\Element\\Text',
            'options' => array (
),
            'attributes' => array (
),
        )));

    }
}
