<h2><?php echo $this->translate('Add Job'); ?></h2>

<ul class="breadcrumb">
    <li><?php echo $this->translate('Furnace'); ?> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url('furnace-crud'); ?>"><?php
        echo $this->translate('Jobs List'); ?></a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url('furnace-crud', array(
            'action' => 'create',
        )); ?>"><?php echo $this->translate('Create Job'); ?></a></li>
</ul>

<fieldset>
    <legend>General</legend>
    <?php echo $this->ztbForm($form); ?>
</fieldset>
