<h2><?php echo $this->translate('Add Job'); ?></h2>

<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('furnace-crud'); ?>"><?php
        echo $this->translate('Jobs List'); ?></a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url('furnace-crud', array(
            'action' => 'create',
        )); ?>"><?php echo $this->translate('Create Job'); ?></a></li>
</ul>

<fieldset>
    <legend>General</legend>
    <?php
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->ztbFormElement($form->get('name'));
    echo $this->ztbFormElement($form->get('description'));
    echo $this->ztbFormElement($form->get('priority'));
    echo $this->ztbFormElement($form->get('schedule'));
    echo $this->ztbFormElement($form->get('startAt'));
    echo $this->furnaceDependency();

    echo $this->ztbFormElement($form->get('submit'));
    echo $this->form()->closeTag($form);
    ?>
</fieldset>
