<h2><?php echo $this->translate('Edit Job'); ?></h2>

<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('furnace-crud'); ?>"><?php
        echo $this->translate('Jobs List'); ?></a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url('furnace-crud', array(
        'action' => 'view',
        'param'  => $job->getName(),
    )); ?>"><?php echo $this->escapeHtml($job->getName()); ?></a> <span class="divider">/</span></li>
    <li><?php echo $this->translate('Edit'); ?></li>
</ul>

<fieldset>
    <legend>General</legend>
    <?php
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->ztbFormElement($form->get('name'));
    echo $this->ztbFormElement($form->get('description'));
    echo $this->ztbFormElement($form->get('priority'));
    echo $this->ztbFormElement($form->get('schedule'));
    echo $this->ztbFormElement($form->get('startAt'));
    echo $this->furnaceDependency($job);

    $submit = $form->get('submit');
    $submit->setAttribute('value', $this->translate('Save Changes'));
    echo $this->ztbFormElement($submit);
    echo $this->form()->closeTag($form);
    ?>
</fieldset>
