<a href="<?php echo $this->url('furnace-crud', array(
    'action' => 'create',
)); ?>" class="btn pull-right">
    <?php echo $this->translate('Create Job'); ?>
</a>

<h2><?php echo $this->translate('Jobs'); ?></h2>

<ul class="breadcrumb">
    <li><?php echo $this->translate('Furnace'); ?> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url('furnace-crud'); ?>"><?php
        echo $this->translate('Jobs List'); ?></a></li>
</ul>

<?php echo $this->furnaceRefresh(); ?>

<?php echo $this->furnaceJobList($jobs, true); ?>

<div class="btn-group pull-right">
    <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown" href="#">
        Admin
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="#" class="mass-action" data-src="<?php echo $this->url('furnace-cmd', array(
            'action' => 'delete-many',
        )); ?>">Delete</a></li>

        <li class="divider"></li>

        <li><a href="#" class="mass-action" data-src="<?php echo $this->url('furnace-cmd', array(
            'action' => 'reset-many',
        )); ?>">Reset</a></li>
    </ul>
</div>

<div class="btn-group">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        Action
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="#" class="mass-action" data-src="<?php echo $this->url('furnace-cmd', array(
            'action' => 'run-many',
        )); ?>">Run Now</a></li>

        <li class="divider"></li>

        <li><a href="#" class="mass-action" data-src="<?php echo $this->url('furnace-cmd', array(
            'action' => 'mark-completed-many',
        )); ?>">Mark Complete</a></li>

        <li><a href="#" class="mass-action" data-src="<?php echo $this->url('furnace-cmd', array(
            'action' => 'mark-incomplete-many',
        )); ?>">Mark Incomplete</a></li>
    </ul>
</div>
