<h2><?php echo $this->escapeHtml($job->getName()); ?>
    <?php if ($description = $job->getDescription()): ?>
        <small>- <?php echo $this->escapeHtml($description); ?></small>
    <?php endif; ?>
</h2>

<ul class="breadcrumb">
    <li><a href="<?php echo $this->url('furnace-crud'); ?>"><?php
        echo $this->translate('Jobs List'); ?></a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url('furnace-crud', array(
        'action' => 'view',
        'param' => $job->getName(),
    )); ?>"><?php echo $this->escapeHtml($job->getName()); ?></a></li>
</ul>

<?php /* Poll with ajax for changes to the job that require a page update */ ?>
<div id="job-active" data-status-src="<?php echo $this->url('furnace-ajax', array(
    'action' => 'poll-changes',
    'param'  => $job->getName(),
)); ?>" data-job="<?php echo $this->escapeHtmlAttr(json_encode($job->export())); ?>"></div>

<?php if ($job->getError()): ?>
    <div class="alert alert-error">
        <?php echo $this->translate('This job reported an error when it was last run:'); ?>
        <ul>
        <?php foreach ($job->getMessages() ?: array() as $message): ?>
            <li><?php echo $this->escapeHtml($message); ?></li>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

<div class="btn-group pull-right">
    <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown" href="#">
        <?php echo $this->translate('Admin'); ?>
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li><a href="<?php echo $this->url('furnace-cmd', array(
            'action' => 'delete',
            'param'  => $job->getName(),
        )); ?>"><?php echo $this->translate('Delete'); ?></a></li>

        <li class="divider"></li>

        <li><a href="<?php echo $this->url('furnace-cmd', array(
            'action' => 'reset',
            'param'  => $job->getName(),
        )); ?>"><?php
            echo $this->translate('Reset'); ?></a></li>
    </ul>
</div>
<div class="btn-group">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <?php echo $this->translate('Actions'); ?>
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <?php if ($job->isCompleted()): ?>
            <li><a href="<?php echo $this->url('furnace-cmd', array(
                'action' => 'run',
                'param'  => $job->getName(),
            )); ?>"><?php echo $this->translate('Re-Run Now'); ?></a></li>
            <li class="divider"></li>

        <?php elseif (!$job->isStarted()): ?>
            <li><a href="<?php echo $this->url('furnace-cmd', array(
                'action' => 'run',
                'param'  => $job->getName(),
            )); ?>"><?php echo $this->translate('Run Now'); ?></a></li>
            <li class="divider"></li>

        <?php elseif ($job->isStarted()): ?>
            <li><a href="<?php echo $this->url('furnace-cmd', array(
                'action' => 'kill',
                'param'  => $job->getName(),
            )); ?>"><?php echo $this->translate('Stop Execution'); ?></a></li>
            <li class="divider"></li>

        <?php endif; ?>

        <li><a href="<?php echo $this->url('furnace-crud', array(
            'action' => 'edit',
            'param'  => $job->getName(),
        )); ?>"><?php echo $this->translate('Edit'); ?></a></li>

        <?php if (!$job->isCompleted()): ?>
            <li><a href="<?php echo $this->url('furnace-cmd', array(
                'action' => 'mark-completed',
                'param'  => $job->getName(),
            )); ?>"><?php echo $this->translate('Mark Completed'); ?></a></li>
        <?php else: ?>
            <li><a href="<?php echo $this->url('furnace-cmd', array(
                'action' => 'mark-incomplete',
                'param'  => $job->getName(),
            )); ?>"><?php echo $this->translate('Mark Incomplete'); ?></a></li>
        <?php endif; ?>
    </ul>
</div>

<form class="form-horizontal">
<fieldset>
    <legend><?php echo $this->translate('General'); ?></legend>
    <div class="control-group control-text">
        <label class="control-label"><?php echo $this->translate('Schedule'); ?></label>
        <div class="controls">
            <?php echo $this->furnaceFrequency($job); ?>
        </div>
    </div>
    <div class="control-group control-text">
        <label class="control-label"><?php echo $this->translate('Priority'); ?></label>
        <div class="controls">
            <?php echo number_format($job->getPriority(), 0); ?>
        </div>
    </div>
    <div class="control-group control-text">
        <label class="control-label"><?php echo $this->translate('Status'); ?></label>
        <div class="controls">
            <?php echo $this->furnaceStatus($job); ?>

            <?php if ($job->isStarted()): ?>
                <em><small><?php printf($this->translate('Started at %s, running for %s.'),
                    $job->getStartedAt()->format('Y-m-d H:i:s'),
                    $this->furnaceFormat($job->getStartedAt()->getTimestamp())
                ); ?></small></em>

            <?php elseif ($job->isQueued()): ?>
                <em><small><?php printf($this->translate('Queued at %s (%s).'),
                    $job->getQueuedAt()->format('Y-m-d H:i:s'),
                    $this->furnaceFormat($job->getQueuedAt()->getTimestamp())
                ); ?></small></em>

            <?php endif; ?>
        </div>
    </div>
    <?php if ($elapsed): ?>
        <div class="control-group control-text">
            <label class="control-label"><?php echo $this->translate('Running Time'); ?></label>
            <div class="controls">
                <?php echo $this->furnaceFormat(time() - $elapsed); ?>
            </div>
        </div>
    <?php endif; ?>
    <?php if ($dependencies): ?>
        <div class="control-group control-text">
            <label class="control-label"><?php echo $this->translate('Dependencies'); ?></label>
            <div class="controls">
                <?php echo $this->furnaceJobList($dependencies); ?>
            </div>
        </div>
    <?php endif; ?>
</fieldset>

<?php if ($job->isStarted()): ?>
<fieldset>
    <legend><?php echo $this->translate('Running'); ?></legend>
    <?php if ($job->getPidOf()): ?>
        <div class="control-group control-text">
            <label class="control-label"><?php echo $this->translate('Process ID'); ?></label>
            <div class="controls">
                #<?php echo $job->getPidOf(); ?> <code><?php echo $this->escapeHtml($job->getPidCmd()); ?></code>
                Started at <?php echo $job->getStartedAt()->format('Y-m-d H:i:s'); ?>
            </div>
        </div>
    <?php endif; ?>
</fieldset>
<?php endif; ?>

<?php if ($logs = $job->getLogs()): ?>
<fieldset>
    <?php foreach ($logs as $log): ?>
        <?php echo $this->furnaceLog($job, $log); ?>
    <?php endforeach; ?>
</fieldset>
<?php endif; ?>

<?php if ($history = $job->getHistory()): ?>
<fieldset>
    <legend><?php echo $this->translate('History'); ?></legend>
    <table class="table" id="job-history">
    <thead>
        <tr>
            <th class="column-status"><?php echo $this->escapeHtml('Status'); ?></th>
            <th class="column-started"><?php echo $this->escapeHtml('Started'); ?></th>
            <th class="column-ended"><?php echo $this->escapeHtml('Ended'); ?></th>
            <th class="column-memory"><?php echo $this->escapeHtml('Peak Memory'); ?></th>
            <th class="column-running-time"><?php echo $this->escapeHtml('Running Time'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($history as $index => $item): ?>
        <tr>
            <td class="column-status">
                <?php if ($item->getFailedAt()): ?>
                    <span class="label label-important">Failed</span>
                <?php else: ?>
                    <span class="label label-success">Success</span>
                <?php endif; ?>
            </td>
            <td class="column-started">
                <?php echo $item->getStartedAt()->format('Y-m-d H:i:s'); ?>
            </td>
            <td class="column-ended">
                <?php if ($endedAt = $item->getFailedAt() ?: $item->getCompletedAt()): ?>
                    <?php echo $endedAt->format('Y-m-d H:i:s'); ?>
                <?php endif; ?>
            </td>
            <td class="column-memory">
                <?php
                    if (($stats = $item->getStats()) && isset($stats['VmPeak'])) {
                        printf('%s', $stats['VmPeak']);
                    } else {
                        echo 'n/a';
                    }
                ?>

                <a href="<?php echo $this->url('furnace-ajax', array(
                    'action' => 'get-usage-stats',
                    'param' => $job->getName(),
                    'param2' => $index + 1,
                )); ?>" class="job-status"><small>details</small></a>
            </td>
            <td class="column-running-time">
                <?php
                $elapsed = $endedAt->getTimestamp() - $item->getStartedAt()->getTimestamp();
                echo $this->furnaceFormat(time() - $elapsed);
                ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    </table>
</fieldset>
<?php endif; ?>

</form>
