<h2><?php echo $this->escapeHtml($job->getName()); ?>
    <?php if ($description = $job->getDescription()): ?>
        <small>- <?php echo $this->escapeHtml($description); ?></small>
    <?php endif; ?>
</h2>

<ul class="breadcrumb">
    <li><?php echo $this->translate('Furnace'); ?> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url('furnace-crud'); ?>"><?php
        echo $this->translate('Jobs List'); ?></a> <span class="divider">/</span></li>
    <li><?php echo $this->translate('View'); ?> <em><?php
        echo $this->escapeHtml($job->getName()); ?></em></li>
</ul>

<div class="job-commands">
    <?php if ($job->isCompleted()): ?>
        <a href="<?php echo $this->url('furnace-cmd', array(
            'action' => 'run',
            'param'  => $job->getName(),
        )); ?>" class="btn"><?php echo $this->translate('Re-Run'); ?></a>
    <?php elseif (!$job->isStarted()): ?>
        <a href="<?php echo $this->url('furnace-cmd', array(
            'action' => 'run',
            'param'  => $job->getName(),
        )); ?>" class="btn btn-info"><?php echo $this->translate('Run'); ?></a>
    <?php endif; ?>

    <a href="<?php echo $this->url('furnace-cmd', array(
        'action' => 'mark-completed',
        'param'  => $job->getName(),
    )); ?>" class="btn"><?php echo $this->translate('Mark Completed'); ?></a>

    <a href="<?php echo $this->url('furnace-crud', array(
        'action' => 'edit',
        'param'  => $job->getName(),
    )); ?>" class="btn"><?php echo $this->translate('Edit'); ?></a>

    <a href="<?php echo $this->url('furnace-cmd', array(
        'action' => 'delete',
        'param'  => $job->getName(),
    )); ?>" class="btn btn-danger pull-right"><?php echo $this->translate('Delete'); ?></a>

    <a href="<?php echo $this->url('furnace-cmd', array(
        'action' => 'reset',
        'param'  => $job->getName(),
    )); ?>" class="btn pull-right" style="margin-right: 0.5em;"><?php
        echo $this->translate('Reset'); ?></a>
</div>

<?php if ($job->getError()): ?>
    <div class="alert alert-error">
        <?php echo $this->translate('This job reported an error when it was last run.'); ?>
    </div>
<?php endif; ?>

<form class="form-horizontal">
<fieldset>
    <legend><?php echo $this->translate('General'); ?></legend>
    <div class="control-group">
        <label class="control-label"><?php echo $this->translate('Schedule'); ?></label>
        <div class="controls control-text">
            <?php echo $this->furnaceFrequency($job); ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label"><?php echo $this->translate('Priority'); ?></label>
        <div class="controls control-text">
            <?php echo number_format($job->getPriority(), 0); ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label"><?php echo $this->translate('Status'); ?></label>
        <div class="controls control-text">
            <?php echo $this->furnaceStatus($job); ?>
        </div>
    </div>
    <?php if ($elapsed): ?>
        <div class="control-group">
            <label class="control-label"><?php echo $this->translate('Running Time'); ?></label>
            <div class="controls control-text">
                <?php echo $this->furnaceFormat(time() - $elapsed); ?>
            </div>
        </div>
    <?php endif; ?>
</fieldset>

<?php if ($history = $job->getHistory()): ?>
<fieldset>
    <legend><?php echo $this->translate('History'); ?></legend>
    <table class="table" id="job-history">
    <thead>
        <tr>
            <th class="column-status"><?php echo $this->escapeHtml('Status'); ?></th>
            <th class="column-started"><?php echo $this->escapeHtml('Started'); ?></th>
            <th class="column-ended"><?php echo $this->escapeHtml('Ended'); ?></th>
            <th class="column-memory"><?php echo $this->escapeHtml('Peak Memory'); ?></th>
            <th class="column-running-time"><?php echo $this->escapeHtml('Running Time'); ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($history as $index => $item): ?>
        <tr>
            <td class="column-status">
                <?php if ($item->getFailedAt()): ?>
                    <span class="label label-important">Failed</span>
                <?php else: ?>
                    <span class="label label-success">Success</span>
                <?php endif; ?>
            </td>
            <td class="column-started">
                <?php echo $item->getStartedAt()->format('Y-m-d H:i:s'); ?>
            </td>
            <td class="column-ended">
                <?php $endedAt = $item->getFailedAt() ?: $item->getCompletedAt(); ?>
                <?php echo $endedAt->format('Y-m-d H:i:s'); ?>
            </td>
            <td class="column-memory">
                <?php
                    if (($stats = $item->getStats()) && isset($stats['VmPeak'])) {
                        printf('%s', $stats['VmPeak']);
                    } else {
                        echo 'n/a';
                    }
                ?>

                <a href="<?php echo $this->url('furnace-ajax', array(
                    'action' => 'get-usage-stats',
                    'param' => $job->getName(),
                    'param2' => $index + 1,
                )); ?>" class="job-status"><small>details</small></a>
            </td>
            <td class="column-running-time">
                <?php
                $elapsed = $endedAt->getTimestamp() - $item->getStartedAt()->getTimestamp();
                echo $this->furnaceFormat(time() - $elapsed);
                ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
    </table>
</fieldset>
<?php endif; ?>

</form>
