<?php
$this->docType('HTML5');
echo $this->doctype();

$this->headMeta()
    ->appendName('viewport', 'width=device-width');

$this->headLink()
    ->appendStylesheet($this->url('furnace-css'))
    ->appendStylesheet('//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css');

$this->inlineScript()
    ->appendFile($this->url('furnace-js'));

?>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7 ie6" lang="en"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8 ie7" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9 ie8" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
<meta charset="utf-8">
<?php echo $this->renderContent()->head(); ?>
<?php echo $this->headMeta(); ?>
<?php echo $this->headLink(); ?>
<link rel="icon" href="/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
<?php
echo $this->headStyle();
echo $this->headScript();
?>
</head>
<body>
<div class="navbar navbar-inverse">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="http://contain-project.org/furnace">Furnace</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="">
                        <a href="<?php echo $this->url('furnace-crud'); ?>"><?php echo $this->translate('Jobs List'); ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="jobs-container">
    <div class="jobs-content">
        <?php
        $this->flashMessenger()
            ->setMessageOpenFormat('<div%s>')
            ->setMessageCloseString('</div>')
            ->setMessageSeparatorString('<br />');

        foreach (array('success', 'error', 'info') as $namespace) {
            echo $this->flashMessenger()->render(
                $namespace,
                array('alert', 'alert-' . $namespace)
            );
        }
        echo $this->content;
        ?>
    </div>
</div>
<div id="job-spinner" class="job-spinner">
    <div class="floatingBarsG">
        <div class="blockG" id="rotateG_01">
        </div>
        <div class="blockG" id="rotateG_02">
        </div>
        <div class="blockG" id="rotateG_03">
        </div>
        <div class="blockG" id="rotateG_04">
        </div>
        <div class="blockG" id="rotateG_05">
        </div>
        <div class="blockG" id="rotateG_06">
        </div>
        <div class="blockG" id="rotateG_07">
        </div>
        <div class="blockG" id="rotateG_08">
        </div>
    </div>
</div>
<footer>
    <div id="footer">
        Furnace is open source software released under the <a href="http://www.opensource.org/licenses/bsd-license.php">BSD-2 license</a> by <a href="http://andrewkandels.com/">Andrew Kandels</a>.
    </div>
</footer>
<?php echo $this->inlineScript(); ?>
</body>
</html>
